"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class tof_lcmt(object):
    __slots__ = ["tof_id", "tof_time", "tof_data"]

    __typenames__ = ["int64_t", "int64_t", "float"]

    __dimensions__ = [None, None, [64]]

    def __init__(self):
        self.tof_id = 0
        self.tof_time = 0
        self.tof_data = [ 0.0 for dim0 in range(64) ]

    def encode(self):
        buf = BytesIO()
        buf.write(tof_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.tof_id, self.tof_time))
        buf.write(struct.pack('>64f', *self.tof_data[:64]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tof_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tof_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tof_lcmt()
        self.tof_id, self.tof_time = struct.unpack(">qq", buf.read(16))
        self.tof_data = struct.unpack('>64f', buf.read(256))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if tof_lcmt in parents: return 0
        tmphash = (0x136b1cabff7d7647) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tof_lcmt._packed_fingerprint is None:
            tof_lcmt._packed_fingerprint = struct.pack(">Q", tof_lcmt._get_hash_recursive([]))
        return tof_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", tof_lcmt._get_packed_fingerprint())[0]

